kind: pipeline
type: docker
name: default

steps:
  - name: deploy
    image: plugins/docker
    settings:
      registry: registry.d1v3.de
      repo: registry.d1v3.de/infomentor
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: ["commit_${DRONE_COMMIT}","build_${DRONE_BUILD_NUMBER}", "latest"]

